### ISSUE TITLE
Support applicationData hash

### ISSUE THREAD

**Issue by rwdaigle** [spreedly/gala#2]
There's a hash of `applicationData` contained in the token. We should expose it if it exists.

> Hash of the applicationData property of the original PKPaymentRequest object. If the value of that property is nil, this key is omitted.

**Comment by mrezentes** [comment]
The applicationData is in the header info of the payment_data.  Since the payment_data is exposed, this piece of info is also exposed. Unless you were looking to take it from the format it is in from Apple "SHA–256 hash, hex encoded as a string" and put it into a more readable form.  I favor closing since the info is available.

**Comment by rwdaigle** [comment]
Since it's just a hash of the original values, yes, we can just expose it as it will be once sig verification is merged.
